### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/mynamenecklace-shoov#3]
http://www.mynamenecklace.com/

**Comment by DavidKohav** [comment]
Can you change the name?>

**Comment by amitaibu** [comment]
added you to repo

**Comment by mldk-tech** [comment]
:+1:

**Comment by DavidKohav** [comment]
![ct8uyopu8ae01rt_290](https://cloud.githubusercontent.com/assets/5812423/12583039/5725b902-c449-11e5-9d10-ca10778d1f88.jpg)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/22075

**Comment by mldk-tech** [comment]
http://gfycat.com/UntriedLegitimateBooby
